# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_position_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog, QLineEdit, QMessageBox

from controlsystem import Check


class NewPositionWindow(QDialog):


    def setupUi(self, new_position_window,controlsystem,model_empl,empl_list):
        new_position_window.setObjectName("new_empl_window")
        new_position_window.resize(400, 300)
        new_position_window.setStyleSheet("background-color: rgb(229, 224, 255);\n"
"font: 75 10pt \"System\";\n"
"border: 2px solid #c0b7ff; /* Цвет рамки и ее толщина */\n"
"border-radius: 10px; /* Закругление углов */\n"
"\n"
"")
        self.new_position_window=new_position_window
        self.employees_list=empl_list
        self.controlsystem=controlsystem
        self.model_empl=model_empl
        self.btn_OK = QtWidgets.QDialogButtonBox(new_position_window)
        self.btn_OK.setGeometry(QtCore.QRect(20, 240, 361, 51))
        self.btn_OK.setStyleSheet("QPushButton {\n"
"border-radius:  10px;\n"
"background-color: rgb(240, 235, 255);\n"
"alternate-background-color: rgb(255, 255, 255);\n"
"border-color: rgb(197, 170, 255);\n"
"selection-color: rgb(246, 247, 255);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(211, 199, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(255, 255, 255);\n"
"}")
        self.btn_OK.setOrientation(QtCore.Qt.Horizontal)
        self.btn_OK.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.btn_OK.setObjectName("btn_OK")
        self.text_label_salary = QtWidgets.QLabel(new_position_window)
        self.text_label_salary.setGeometry(QtCore.QRect(30, 30, 351, 51))
        self.text_label_salary.setStyleSheet("background-color: rgb(247, 242, 255);\n"
"font: 75 10pt \"System\";\n"
"border: 0px solid #c0b7ff; /* Цвет рамки и ее толщина */\n"
"border-radius: 10px; /* Закругление углов */\n"
"")
        self.text_label_salary.setObjectName("text_label_salary")
        self.inp_new_position = QtWidgets.QLineEdit(new_position_window)
        self.inp_new_position.setGeometry(QtCore.QRect(70, 130, 261, 61))
        self.inp_new_position.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.inp_new_position.setStyleSheet("background-color: rgb(247, 242, 255);\n"
"font: 75 10pt \"System\";\n"
"border: 0px solid #c0b7ff; /* Цвет рамки и ее толщина */\n"
"border-radius: 10px; /* Закругление углов */\n"
"")
        self.inp_new_position.setObjectName("inp_new_position")

        self.retranslateUi(new_position_window)
        self.btn_OK.accepted.connect(self.change_position) # type: ignore
        self.btn_OK.rejected.connect(new_position_window.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(new_position_window)
    def change_position(self):
        index = self.employees_list.currentIndex()
        new_position=self.inp_new_position.text()
        if index.isValid() and Check.check_position_answer(new_position):
            self.model_empl.removeRow(index.row())
            self.controlsystem.change_position(index.row(),new_position)
            self.controlsystem.save_json()
            self.new_position_window.close()
        else:
            error_dialog = QMessageBox()
            error_dialog.setIcon(QMessageBox.Critical)
            error_dialog.setText("УУПС ОШИБОЧКА!")
            error_dialog.setInformativeText("Возможно, такой должности не существует")
            error_dialog.setWindowTitle("ERROR")
            error_dialog.exec_()
            error_dialog.close()
    def retranslateUi(self, new_position_window):
        _translate = QtCore.QCoreApplication.translate
        new_position_window.setWindowTitle(_translate("new_empl_window", "Dialog"))
        self.text_label_salary.setText(_translate("new_empl_window", "Введите, пожалуйста, новую должность\n"
" для сотрудника"))
